### ISSUE TITLE
vyssi limit na dlazdice pri stahovani

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marvertin/geokuk#110]
```
aby bylo mozno dat stahovat dlazdice na jednou pro celou republiku pri max zoomu
```

Original issue reported on code.google.com by `c...@lordcyber.net` on 5 Jan 2014 at 12:15

**Comment by marvertin** [comment]
To by se asi nemuselo líbit Seznamu, těžko se to dá nějak rozumně odůvodnit.
