### ISSUE TITLE
Měřítko

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marvertin/geokuk#123]
```
Měřítko upravit tak aby nezakrývalo polovinu souřadnic na mřížce (osa 
X).
```

Original issue reported on code.google.com by `not_regi...@centrum.cz` on 15 Sep 2014 at 12:37

Attachments:
* [meritko geokuk.jpg](https://storage.googleapis.com/google-code-attachments/geokuk/issue-123/comment-0/meritko geokuk.jpg)

**Comment by Danstahr** [comment]
Opraveno.
