### ISSUE TITLE
Instalace nového GEOKUKU

### ISSUE THREAD

**Issue by artavas** [marvertin/geokuk#132]
Zdravím.
Mám problém.Nejde mi nainstalovat nejnovější verze Geokuku 4.0.0.
Kde mám chybu?
Předem děkuji za odpověď.
Libor

**Comment by marvertin** [comment]
Musíš nejdříve popsat, jak se problém projevuje. Napiš co děláš, co čekáš, že se stane a co se stalo.
Martin

**Comment by pavelvanecekcz** [comment]
Zrejme nefunguje automaticka aktualizace napr,pomoci exportniho makra do Geogetu a take nefunguji odkazy ve verzi 3.5.1 na stazeni aktualizaci, nebo odkaz na web.
Ja jsem si ted stahnul jar a exe a budu chvli patrat jak na to, aby mi fungovalo spusteni z Geogetu bez te otravne hlasky java run.

**Comment by pavelvanecekcz** [comment]
Tak jen doplnuji, ze jsem stahnul novy jar, prejmenoval na geokuk.jar, umistil do slozky c:\Users\<uzivatel>\AppData\Roaming\GeoGet\script\geokuk\ a do souboru geokuk_version.txt napsal 4.0.0 .
Vse ze zda, ze slape jak ma.

**Comment by artavas** [comment]
Nazdárek.
Prosím Tě a kde jsi ho stáhnul?Jsem jen průměrný uživatel pc.
Díky moc Libor

2016-02-21 18:56 GMT+01:00 pavelvanecekcz <notifications@github.com>:

**Comment by arozehnal** [comment]
Stahovat lze zde https://github.com/marvertin/geokuk/releases/tag/v4.0.0

**Comment by artavas** [comment]
Nazdárek.
Promiň,že tě zase otravuji.Mi ten geokuk nejde nainstalovat.
Libor-Artavas

2016-02-21 22:11 GMT+01:00 arozehnal <notifications@github.com>:

**Comment by arozehnal** [comment]
to Libor-Artavas: mohl bys přesně popsat co jsi udělal ty, a co to pak vypsalo.
Přikládat lze i screenshoty :-)

**Comment by artavas** [comment]
Tady jsem Ti v příloze poslal,kde to mám uloženo.

2016-02-25 17:37 GMT+01:00 arozehnal <notifications@github.com>:

**Comment by artavas** [comment]
Pak by tu byla ještě možnost.Mám teamwiever jestli by jsi mi to nemohl
prosím nainstalovat přes něj do geogetu?


Dne 25. února 2016 17:42 Libor Kořán <libor.koran@gmail.com> napsal(a):

**Comment by Danstahr** [comment]
Ahoj,

Az prijedu domu, muzu pomoct. Idealni by bylo upravit to Geogeti makro, aby
to fungovalo samo.

**Comment by artavas** [comment]
Tak to by bylo super,kdyby jsi byl tak hodný a pomohl.Jak jsem minule
psal,jsem jen běžný uživatel pc,ale zas tak upravovat to mi moc nejde.

Dne 25. února 2016 17:59 Dan Stahr <notifications@github.com> napsal(a):

> Ahoj,
>
> Az prijedu domu, muzu pomoct. Idealni by bylo upravit to Geogeti makro, aby
> to fungovalo samo.

**Comment by Danstahr** [comment]
Kdyžtak se ozvi na mail, ať tu nespamujeme. dan.stahr@gmail.com

**Comment by Danstahr** [comment]
Vyřešeno.

**Comment by artavas** [comment]
Nazdárek.
Díky za informaci a ještě jednou děkuji,za instalaci GEOKUKU.
Přeji hezký večer
Libor

2016-02-27 20:43 GMT+01:00 Dan Stahr <notifications@github.com>:
