### ISSUE TITLE
Místo ikony foťáku vedle souborů s obrázky je na mapě jen červený čtvereček.

### ISSUE THREAD

**Issue by marvertin** [marvertin/geokuk#133]
Ve stromu kešoidů Dan umožnil i přidaní souborů s obrázky. V jedné verzi měly obrázky na mapě ikonu foťáku (naprosto intuitivní), ale nyní mají obecnou ikonu červené krychličky. Nešlo by nějak nanutit, aby GK zobrazoval specifickou ikonu pro obrázky? Třeba podle přípony souborů? Mám řadu vlastních obecných kategorii bodů (věnuji se waymarkingu :-)) a u nich nastavení vlastní ikony zvládám. Tam je výhoda, že GPX s body mohu editovat, ale u těch *JPG, *PNG toto není možné.

**Comment by arozehnal** [comment]
Tohle nebude bug, ale moje blbost :-(
Cca před 1,5 rokem jsem s Danem řešil zobrazení vlastních ikon v GK. V jednu chvíli se mi zdálo, že to máme zvládnuté, ale pak jsem zjistil, že se mi naopak zobrazují jen ty body s mými ikonami (ikony kešek se nezobrazovaly OK).
Metodou pokus omyl jsem na dosáhl toho stavu, že se mi zobrazovaly správně všechny 'integrované' ikony (např. kategorie kešek), ale i ty moje vlastní ikony.
Dosáhl jsem toho tak, že jsem:
a) z jaru GK vykopíroval adresář map s obsahem  a dal jej do HOME adresáře GK (v mém případě e:\Geokuk)
b) v adresáři e:\Geokuk\map mám rozbalenou strukturu roze.zip
[roze.zip](https://github.com/marvertin/geokuk/files/139857/roze.zip)
c) v menu GK->Ikony jsem pak měl možnost přepínat mezi sadami ikon Standard a roze
     Sada roze zobrazovala OK moje vlastní ikony i ty  'integrované'.
Cca před 14 dny jsem přešel z Win XP na Win 7, adresářové struktury jsem prostě překopíroval, a zdálo se mi (pokud jde o ikony v GK) vše OK. 
Teď ale vidím, že na těch Win7 mi:
a) ani jedna sada ikon nezobrazuje  'integrované' ikony (ikony kešek)
b) sada roze mi zobrazuje OK vlastní ikony
c) sada Standard zobrazuje správně ikonu foťáku u bodů, kde jsou zdrojem kešoidu obrázky

Myslím, že když se podaří vyřešit 'řádně' použití vlastních ikon, tak se automaticky pořeší i tento pseudobug.

**Comment by arozehnal** [comment]
Ufff, tak už se mi zobrazují ikony i normálních keší na tom oživovaném PC s Win7. Laboroval jsem pořád s generováním zdrojů bodů a klikal na ikony na toolbaru, ale tam nebyl problém. Nakonec stačilo jednou překliknout v selectboxu z Všechnz -> Lovené, resp. zpět a moje i integrované ikony se zobrazují.
Pak stačilo do správného podadresáře v  e:\Geokuk\map dokopírovat pic!Photo.gif a výsledek je tento :-) -> 
![2016-02-22 21_21_40-geokuk](https://cloud.githubusercontent.com/assets/8810398/13232388/3ba7741a-d9af-11e5-9afd-b8d758ae55a1.png)

**Comment by marvertin** [comment]
Ikona foťáku se zobrazuje, takže zavírám.
