### ISSUE TITLE
Vyjimka pri zpracovani na pozadi - exc31a1

### ISSUE THREAD

**Issue by happiskovi** [marvertin/geokuk#141]
Zdravím! 
Po nainstalování poslední verze GeoKuk 4.1.2 mi přestalo fungovat zobrazování ikon keší v mapě. Z GeoGetu se po spuštění pluginu GeoKuk soubor keší vyexportuje do adresáře (kesky20160307....gpx), ale před zobrazením v mapě se vypíše chybové hlášení "Vyjimka při zpracování na pozadí (exc31a1). 
Verze Java 8 Update 73. Kde by mohla být chybka?

**Comment by Danstahr** [comment]
Mrknu.

**Comment by Danstahr** [comment]
Můžeš přiložit celou výjimku?

**Comment by happiskovi** [comment]
Při kopírování výjimky jsem si všimla, že je tam nějaký problém se souborem cesty, který jsem dříve vytvořila. Soubor

**Comment by happiskovi** [comment]
Při kopírování výjimky jsem si všimla, že je tam nějaký problém se souborem
cesty, který jsem dříve vytvořila. Soubor jsem smazala z adresáře cest a
nyní se GeoKuk bez problémů otevře z GeoGetu, včetně vyexportovaných ikon.
Omlouvám se za nahlášení tohoto problému a za ztrátu tvého času, ale díky
tomu jsme aspoň přišli na problém s cestou:-)
Díky za tvou rychlou reakci!

Dne 7. března 2016 21:08 Dan Stahr <notifications@github.com> napsal(a):
