### ISSUE TITLE
Verze 5.0.0 Nenačte všechny keše z GPX 

### ISSUE THREAD

**Issue by Bohusz** [marvertin/geokuk#149]
Zdá se, že verze 5.0.0, byť zobrazuje mapy pro celý svět, omezuje načítaní keší na oblast Evropy.
Z přiloženého GPX [Japonsko+Istanbul.zip](https://github.com/marvertin/geokuk/files/196972/Japonsko.Istanbul.zip) načte jen 109 keší (ty v Turecku). Viz. _screenshot_:

![Přehled zdrojů kešoidů](https://cloud.githubusercontent.com/assets/1022442/14165410/eb0d00ca-f708-11e5-9056-3c66a6040932.png)

**Comment by Danstahr** [comment]
Opraveno v PR #148

**Comment by marvertin** [comment]
Problém byl v zapomenutém omezení.
