### ISSUE TITLE
Verze 5.0.0 nenačte žádné keše ze souboru kesyk.geokuk

### ISSUE THREAD

**Issue by Bohusz** [marvertin/geokuk#150]
Když vygeneruji soubor ve formátu **geokuk:exportversion=2**, verze 5.0.0 nenačte ani jedinou. Viz. řádek **kešky.geokuk**, sloupec "WP Celkem":

![20160331-062439001](https://cloud.githubusercontent.com/assets/1022442/14165482/a778ffd4-f709-11e5-8f48-5c562e8dca53.png)

Přikládám soubor [kesky.zip](https://github.com/marvertin/geokuk/files/196979/kesky.zip), který obsahuje stejná data, jako GPX v _issue_ #149.

**Comment by Danstahr** [comment]
Opraveno v PR #148

**Comment by Danstahr** [comment]
Kouknu na to.

**Comment by marvertin** [comment]
Problém byl v zapomenutém omezení.

**Comment by Bohusz** [comment]
To jako že ta omezení byla dvě, jedno pro **.geokuk** a druhé pro **.gpx** formát? Protože oba soubory, co jsem přikládal, měly IMO stejný obsah. Nebo jsem se spletl já a v **.geokuk** nebylo Turecko?

**Comment by Danstahr** [comment]
Oba pripady zpusobovala stejna chyba a oba pripady tak byly opraveny jednou zmenou. Pokud vim, v obou souborech byl stejny obsah.
