### ISSUE TITLE
Nesprávný export mapy do PNG - posunutí ikon

### ISSUE THREAD

**Issue by JiriBilek** [marvertin/geokuk#157]
Při exportu do png (Soubor-Tisknout, dále volby Obrázek mapy, PNG) dochází ve výsledném souboru i verze 5.0.1 k posunu všech ikon keší i waypointů směrem na západ (doprava). Verze 4.x byla a je v pořádku.
Přikládám dump, s oknem geokuku a png.

![geokuk-posunuti-ikon](https://cloud.githubusercontent.com/assets/15474360/18046960/aa4d2ff8-6dda-11e6-9919-cb8e0ac2de6f.png)

**Comment by pschonmann** [comment]
Rekl bych ze bude souviset s #143

**Comment by JiriBilek** [comment]
Souhlasím, opravdu to dělá chybu jen na některé kombinace (zoom mapy geokuk) / (zoom souboru).
Zavírám požadavek, je duplicitní.
