### ISSUE TITLE
nactení GPX

### ISSUE THREAD

**Issue by sweet128** [marvertin/geokuk#176]
Ahoj. Chtěl bych použít geokuk, ale mám problém s načtením některých GPX souborů. Export ze c:geo načte v pořádku, ale export jiného GPX crashne. Ostatní aplikace s tím nemají problém, například do Garmina jdou, nebo do Locusu.
Případně mohu problematický GPX dodat emailem.
Luděk

**Comment by JiriBilek** [comment]
Nehodí to něco v logu (podadresář logs)? Myslím javovskou exception.

**Comment by sweet128** [comment]
Adresář logs nemám, ale hodí chybu přímo do terminálu:

EXC-1-dump-exc8a1: Exception printed at 2021-06-30T05:24:33.608+0200
EXC-1-dump-exc8a1:     render.17 - cz.geokuk.util.lang.FThrowable$ExceptionPrinter.printStackTrace(FThrowable.java:65)
EXC-1-dump-exc8a1:     render.16 - cz.geokuk.util.lang.FThrowable.printStackTrace(FThrowable.java:583)
EXC-1-dump-exc8a1:     render.15 - cz.geokuk.util.lang.FThrowable.printStackTrace(FThrowable.java:577)
EXC-1-dump-exc8a1:     render.14 - cz.geokuk.util.exception.ExceptionDumper.dump(ExceptionDumper.java:194)
EXC-1-dump-exc8a1:     render.13 - cz.geokuk.util.exception.ExceptionDumper.dump(ExceptionDumper.java:94)
EXC-1-dump-exc8a1:     render.12 - cz.geokuk.util.exception.FExceptionDumper.dump(FExceptionDumper.java:40)
EXC-1-dump-exc8a1:     render.11 - cz.geokuk.plugins.kesoid.importek.Nacitac0.nactiBezVyjimky(Nacitac0.java:40)
EXC-1-dump-exc8a1:        ... + 10 hereafter
EXC-1-dump-exc8a1: 1/1 java.lang.NullPointerException #534746572
EXC-1-dump-exc8a1:     1.22 - cz.geokuk.plugins.kesoid.Kesoid.setAuthor(Kesoid.java:186)
EXC-1-dump-exc8a1:     1.21 - cz.geokuk.plugins.kesoid.kind.kes.KesGpxWptProcak.createKes(KesGpxWptProcak.java:96)
EXC-1-dump-exc8a1:     1.20 - cz.geokuk.plugins.kesoid.kind.kes.KesGpxWptProcak.process(KesGpxWptProcak.java:34)
EXC-1-dump-exc8a1:     1.19 - cz.geokuk.plugins.kesoid.kind.kes.KesGpxWptProcak.process(KesGpxWptProcak.java:14)
EXC-1-dump-exc8a1:     1.18 - cz.geokuk.util.procak.ProcakDispatcher$Kolo.dispatch(ProcakDispatcher.java:64)
EXC-1-dump-exc8a1:     1.17 - cz.geokuk.util.procak.ProcakDispatcher$Kolo.access$000(ProcakDispatcher.java:40)
EXC-1-dump-exc8a1:     1.16 - cz.geokuk.util.procak.ProcakDispatcher.dispatch(ProcakDispatcher.java:29)
EXC-1-dump-exc8a1:     1.15 - cz.geokuk.plugins.kesoid.importek.KesoidImportBuilder.addGpxWpt(KesoidImportBuilder.java:86)
EXC-1-dump-exc8a1:     1.14 - cz.geokuk.plugins.kesoid.importek.NacitacGpx.load(NacitacGpx.java:138)
EXC-1-dump-exc8a1:     1.13 - cz.geokuk.plugins.kesoid.importek.NacitacGpx.nacti(NacitacGpx.java:176)
EXC-1-dump-exc8a1:     1.12 - cz.geokuk.plugins.kesoid.importek.NacitacInputStream0.nacti(NacitacInputStream0.java:17)
EXC-1-dump-exc8a1:     1.11 * cz.geokuk.plugins.kesoid.importek.Nacitac0.nactiBezVyjimky(Nacitac0.java:35)
EXC-1-dump-exc8a1:     1.10 - cz.geokuk.plugins.kesoid.importek.MultiNacitac.zpracujJedenFile(MultiNacitac.java:132)
EXC-1-dump-exc8a1:     1.9 - cz.geokuk.plugins.kesoid.importek.MultiNacitac.nacti(MultiNacitac.java:79)
EXC-1-dump-exc8a1:     1.8 - cz.geokuk.plugins.kesoid.importek.MultiNacitacSwingWorker.doInBackground(MultiNacitacSwingWorker.java:44)
EXC-1-dump-exc8a1:     1.7 - cz.geokuk.plugins.kesoid.importek.MultiNacitacSwingWorker.doInBackground(MultiNacitacSwingWorker.java:19)
EXC-1-dump-exc8a1:     1.6 - java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
EXC-1-dump-exc8a1:     1.5 - java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
EXC-1-dump-exc8a1:     1.4 - java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
EXC-1-dump-exc8a1:     1.3 - java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
EXC-1-dump-exc8a1:     1.2 - java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
EXC-1-dump-exc8a1:     1.1 - java.base/java.lang.Thread.run(Thread.java:832)
!!!!! EXC-1: 1/1 java.lang.NullPointerException: null

**Comment by JiriBilek** [comment]
Podle mě to vypadne na tom, že v GPX souboru není u keše zadaný owner (v GPXku by to měl snad být element _groundspeak:placed_by_)

**Comment by sweet128** [comment]
Ano, je to tak. Bylo by možné upravit Geokuk tak, aby to přeskočil? Tohle je jediný program i pro Linux, který funguje. S GPX soubory moc neudělám, jsou odjinud. Dávám příklad, co je u jedné keše vše za elementy:

<wpt lat="49.6915" lon="12.796266666667">
<name>GC2FX0C</name>
<desc><![CDATA[Vodni ptaci by Unknown]]></desc>
<url>https://www.geocaching.com/seek/cache_details.aspx?guid=d929bb17-bd46-4bc4-90e1-783969ad4d49</url>
<urlname><![CDATA[Vodni ptaci]]></urlname>
<sym>Geocache</sym>
<type>Geocache|Unknown Cache</type>
<groundspeak:cache id="1909707" available="True" archived="False" xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1">
<groundspeak:name><![CDATA[Vodni ptaci]]></groundspeak:name>
<groundspeak:type>Unknown Cache</groundspeak:type>
<groundspeak:container>Micro</groundspeak:container>
<groundspeak:difficulty>3.5</groundspeak:difficulty>
<groundspeak:terrain>3</groundspeak:terrain>
<groundspeak:encoded_hints><![CDATA[pred poslednim, vpravo]]></groundspeak:encoded_hints>
<groundspeak:short_description html="True"><![CDATA[Vloženo: 02.06. 2013<br>Drive in: NE<br>Ověřeno: Ověřovačem v listingu]]></groundspeak:short_description>
<groundspeak:long_description html="False"></groundspeak:long_description>
<groundspeak:encoded_hints><![CDATA[pred poslednim, vpravo]]></groundspeak:encoded_hints>
</groundspeak:cache>
</wpt>

**Comment by sweet128** [comment]
`<wpt lat="49.6915" lon="12.796266666667">
<name>GC2FX0C</name>
<desc><![CDATA[Vodni ptaci by Unknown]]></desc>
<url>https://www.geocaching.com/seek/cache_details.aspx?guid=d929bb17-bd46-4bc4-90e1-783969ad4d49</url>
<urlname><![CDATA[Vodni ptaci]]></urlname>
<sym>Geocache</sym>
<type>Geocache|Unknown Cache</type>
<groundspeak:cache id="1909707" available="True" archived="False" xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1">
<groundspeak:name><![CDATA[Vodni ptaci]]></groundspeak:name>
<groundspeak:type>Unknown Cache</groundspeak:type>
<groundspeak:container>Micro</groundspeak:container>
<groundspeak:difficulty>3.5</groundspeak:difficulty>
<groundspeak:terrain>3</groundspeak:terrain>
<groundspeak:encoded_hints><![CDATA[pred poslednim, vpravo]]></groundspeak:encoded_hints>
<groundspeak:short_description html="True"><![CDATA[Vloženo: 02.06. 2013<br>Drive in: NE<br>Ověřeno: Ověřovačem v listingu]]></groundspeak:short_description>
<groundspeak:long_description html="False"></groundspeak:long_description>
<groundspeak:encoded_hints><![CDATA[pred poslednim, vpravo]]></groundspeak:encoded_hints>
</groundspeak:cache>
</wpt>`

**Comment by JiriBilek** [comment]
To je nějaké divné GPXko, chybí mu spousta elementů. Jakým programem jsi ho získal?

**Comment by sweet128** [comment]
Divné? Geoget, Locus, Garmin, c:geo to načtou bez chyb. Je to export z bývalého fináře (finar.cz)

**Comment by JiriBilek** [comment]
1. to GPXko neodpovídá schématu (xsd), proto je divné
2. nesnáším finálkáře

Nevidím důvod, proč bych kvůli nestandardnímu exportu zasahoval do (cizí) aplikace.
