### ISSUE TITLE
Špatně umístěné menu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marvertin/geokuk#85]
```
Hlavní menu by mělo být umístěné na horní liště a ne v okně program. 
S aplikací se pan hůř pracuje, protože se chová jinak, než ostatní 
aplikace. A taky to blbě vypadá :)
```

Original issue reported on code.google.com by `tomas.s...@gmail.com` on 31 Dec 2011 at 10:34

Attachments:
* [Snímek obrazovky 2011-12-31 v 11.31.17.png](https://storage.googleapis.com/google-code-attachments/geokuk/issue-85/comment-0/Snímek obrazovky 2011-12-31 v 11.31.17.png)

**Comment by marvertin** [comment]
Je to Java, tak to asi nepůjde.
