### ISSUE TITLE
Pořadí bodů v lovim.ggt

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marvertin/geokuk#91]
```
Bylo by možné přidávat nové body do lovim.ggt na konec souboru?
Nyní se přidávají nějak 'chaoticky' :-(
```

Original issue reported on code.google.com by `arozeh...@gmail.com` on 3 Mar 2012 at 12:38

**Comment by Danstahr** [comment]
Opraveno v 5cb34e5721a13cf9ad7362eba39438f73e610ddd.
