### ISSUE TITLE
Potlačení zvýraznění definované cesty

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marvertin/geokuk#92]
```
Nebylo by možné potlačit zvýraznění definované cesty?
Např. v select boxu Výlet?

```

Original issue reported on code.google.com by `arozeh...@gmail.com` on 3 Mar 2012 at 12:46

**Comment by marvertin** [comment]
Nerozumím požadavku, zavírám. Pokud vysvětíš, o co jde ozvu se.
